### ISSUE TITLE
I am a noob

### ISSUE THREAD

**Issue by senya1111** [dloscutoff/ascii-piet#3]
I tired running the following command and got the following output.

> python3 ascii2piet.py  test.txt > test.png
>Traceback (most recent call last):
  File "ascii2piet.py", line 203, in <module>
    img = ascii_to_image(ascii_piet, options.size, verbose=options.verbose)
  File "ascii2piet.py", line 122, in ascii_to_image
    img = img.resize((real_width, real_height), resample=Image.Dither.NONE)
  File "/home/####/.local/lib/python3.8/site-packages/PIL/Image.py", line 62, in __getattr__
    raise AttributeError("module '{}' has no attribute '{}'".format(__name__, name))
AttributeError: module 'PIL.Image' has no attribute 'Dither'

Was wondering if you knew the solution??

**Comment by dloscutoff** [comment]
My guess is you've got an older version of Pillow. Try updating it and see if that helps. Or, you can instead try using [this commit](https://github.com/dloscutoff/ascii-piet/commit/5e016263c0ae9edeb5157521b44829adadd621cc) of ASCII-Piet, which uses `Image.NEAREST` (an older approach, now deprecated) instead of `Image.Dither.NONE`.

Thanks for your interest, BTW!
